name: Test and Coverage

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[test]
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

    - name: Run tests with coverage
      env:
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: 6379
      run: |
        coverage run -m pytest
        coverage xml
        coverage-badge -o src/coverage.svg -f

    - name: Generate App Token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Commit coverage badge
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        git config user.name "MuiceAI[bot]"
        git config user.email "216272510+muiceai[bot]@users.noreply.github.com"
        git add src/coverage.svg

        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
        git diff --cached --quiet || git commit -m "🌸更新覆盖率标签喵喵~"
        git push